### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by tambry** [ppelleti/haskell-wiki-bugs#16]
The HaskellWiki is inaccessible over IPv6.

It seems like it should be a fairly easy fix, as Fastly supports IPv6.

**Comment by ppelleti** [comment]
@hgolden @gbaz This is another thing to consider.  I agree it would be good to support IPv6.

**Comment by tambry** [comment]
I dug a bit further and as far as I can tell, it should be as simple as changing the CNAME record on `wiki.haskell.org` from `j.global-ssl.fastly.net` to `dualstack.j.shared.global.fastly.net`. Doing the switch would also enable HTTP/2.

The following works even now over IPv6 using HTTP/2:  
`curl "https://dualstack.j.shared.global.fastly.net/Haskell" -H
"Host:wiki.haskell.org" -k -http2`

**Comment by hgolden** [comment]
@gbaz, @ppelleti: Do you agree with @tambry's proposed change to the wiki.haskell.org CNAME record? (I am unfamiliar with this technology, though I can research it.) If so, who can make the change to the CNAME record. This is really separate from the MediaWiki upgrade AFAICT.

**Comment by ppelleti** [comment]
Yes, I agree that it is a separate thing.  I was never involved in the CDN or the DNS, and do not have access to those.  So @gbaz would need to do it, or give you the ability to do it, or pass it along to someone else who can do it.  (I don't know how many others are involved in haskell.org infrastructure and what their specialties are.)

**Comment by gbaz** [comment]
Thanks for looking into this @tambry! I just made the switch and it appears to work...

**Comment by ppelleti** [comment]
Yes, thanks @tambry!  Let me know if it works for you, and if so, I'll close the bug.

**Comment by tambry** [comment]
I can confirm it works now. Thanks for fixing this!
